### ISSUE TITLE
Create Protobuf schemas from necessary PySyft classes

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft-proto#35]
The following are classes that exist in PySyft that we have no yet migrated to syft-proto, or classes that are in the middle of a refactor and will need to be modified upon completion:

(items in bold are expected to be needed for mobile)

PyTorch
- [x] **`memory_format`**

Numpy
- [ ] `ndarray`
- [ ] `float32`
- [ ] `float64`
- [ ] `int32`
- [ ] `int64`
- [ ] ...any other dtypes...

PySyft Basics
- [ ] `BaseWorker`
- [ ] ~~`VirtualWorker`~~ (can rely on `BaseWorker` serialization for this)
- [ ] ~~`TrainConfig`~~ (deprecated training method should be removed from PySyft)
- [x] `String`

PySyft Pointers and Wrappers
- [ ] `MultiPointerTensor`
- [ ] `ObjectPointer`
- [ ] `ObjectWrapper`
- [x] `PointerPlan`
- [ ] `PointerProtocol`

PySyft Tensors
- [ ] `LoggingTensor`
- [ ] `AutogradTensor`
- [ ] `CRTPrecisionTensor`
- [x] `FixedPrecisionTensor`
- [ ] `GradFunc`
- [ ] `PrivateTensor`
- [ ] `PlaceholderTensor`

PySyft Messaging
- [ ] ~~`Message`~~ (generic message type should not be serialized to Protobuf)
- [x] `Plan` as a list of operations
- [ ] **`Plan` as Torchscript for inference**
- [ ] **`Plan` as Torchscript for training**
- [x] **`State`**
- [x] **`Protocol`**

PySyft Messages
- [x] **`ForceObjectDeleteMessage`**
- [x] `GetShapeMessage`
- [x] `IsNoneMessage`
- [x] **`ObjectMessage`**
- [x] **`ObjectRequestMessage`**
- [x] **`Operation`**
- [x] `PlanCommandMessage`
- [x] `SearchMessage`

PySyft Exceptions
- [x] **`GetNotPermittedError`**
- [x] **`ResponseSignatureError`**

**Comment by gmuraru** [comment]
@tudorcebere what is the status of this? (you were working on this, right?)
