### ISSUE TITLE
Develop end-to-end testing suite for all full system testing in Federated Learning

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft-proto#37]
This issue doesn't need to live in syft-proto, but it must exist as some sort of a Github issue somewhere. This project is probably the best central location for it for now.

This issue describes how we will need to develop a testing suite that can run span multiple repositories, languages, and environments. We want to ensure that our worker libraries (syft.js, KotlinSyft, SwiftSyft, and PySyft's FL Worker) are always working properly with PyGrid. Likewise, we'll need to test this on various versions of syft-proto and Threepio to ensure that our assisting libraries pair nicely with the other various projects. We need to do roughly the following:

- [ ] Create a central Dockerfile to provision and organize all our necessary resources
- [ ] Create model, training plan, and averaging plan and upload them to PyGrid instance
- [ ] Allow syft.js to participate in a round of training
- [ ] Write tests to ensure that PyGrid is updating the model from syft.js round
- [ ] Allow PySyft FL Worker to participate in a round of training
- [ ] Write tests to ensure that PyGrid is updating the model from PySyft FL Worker round

We should ideally cover the following cases, at the minimum:
- [ ] Is the round able to start?
- [ ] Is the round able to take reports?
- [ ] How do we manage a variety of different `server_config`'s?
- ... others we should have? _Let's open a discussion in the comments below._

**Update 29/05/2020 - We do not currently have any plans to include KotlinSyft or SwiftSyft in our end-to-end testing because of their dependence on a live device or an emulator. Until we have the ability to implement these libraries in a "headless" context, they will not be practical to test end-to-end. _We're open to challenging this thought and would love to implement them, but don't see a clear path at the moment._**

**Comment by cereallarceny** [comment]
Clearing @vvmnnnkv as the assignee, as he will be the mentor for this project, but not the assigned person to perform the task. If this issue isn't taken as part of GSoC, then @vvmnnnkv will take the ticket himself. :)
